#pragma once

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR


#define RGB_MATRIX_DEFAULT_HUE 116
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 100

#define RGB_INDICATOR_DEFAULT_HUE 116
#define RGB_INDICATOR_DEFAULT_SAT 255
#define RGB_INDICATOR_DEFAULT_VAL 255
